[package]
name = "epoch_wasmtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.35.3"
wasmtime-wasi = "0.35.3"
anyhow = "1.0"

